//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canchas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Canchas()
        {
            this.Alquileres = new HashSet<Alquileres>();
            this.HorariosCancha = new HashSet<HorariosCancha>();
        }
    
        public int CanchaID { get; set; }
        public int ProveedorID { get; set; }
        public string Nombre { get; set; }
        public string Deporte { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<decimal> PrecioPorHora { get; set; }
        public Nullable<bool> Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alquileres> Alquileres { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosCancha> HorariosCancha { get; set; }
    }
}
