//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquileres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alquileres()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int AlquilerID { get; set; }
        public int UsuarioID { get; set; }
        public int CanchaID { get; set; }
        public System.DateTime FechaAlquiler { get; set; }
        public int DuracionHoras { get; set; }
        public decimal MontoTotal { get; set; }
        public string Estado { get; set; }
        public string CodigoAlquiler { get; set; }
    
        public virtual Canchas Canchas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
