//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaCancha
    {
        public int ReservaID { get; set; }
        public Nullable<int> AlumnoID { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public string Cancha { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
